import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";

const server = new Server({ name: "mcp_codebeamer_parser", version: "1.0.0" }, { capabilities: { tools: {} } });

const SampleSchema = z.object({
  param1: z.string().describe("Sample parameter"),
});

server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "sample_tool",
        description: "A sample tool generated by mcp_agent scaffolding.",
        inputSchema: {
          type: "object",
          properties: {
            param1: { type: "string", description: "Sample parameter" },
          },
          required: ["param1"],
        },
      }
    ],
  };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  
  if (name === "sample_tool") {
    const { param1 } = SampleSchema.parse(args);
    return {
      content: [{ type: "text", text: `Sample tool executed with param1: ${param1}` }],
    };
  }

  throw new Error(`Unknown tool: ${name}`);
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("mcp_codebeamer_parser server running on stdio");
}

main().catch(console.error);
